{{- if .Values.config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.fullname" . }}-config
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config.data }}
    {{ $k }}: "{{ $v }}"
  {{- end }}
{{- end }}