{{- if .Values.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.stringData }}
    {{ $k }}: "{{ $v }}"
  {{- end }}
{{- end }}